// facts.ts — Pure Home 365 Asheville
// Generated by WebMast v3 pipeline. Do not hand edit without regenerating.

export type ServiceArea = {
  city: string;
  state: string;
};

export type Service = {
  name: string;
  slug: string;
  description: string;
  blurb: string;
};

export type Offer = {
  headline: string;
  detail: string;
};

export type Hours = {
  day: string;
  open: string | null;
  close: string | null;
};

export type ClientFacts = {
  companyName: string;
  tagline: string;
  phone: string;
  phoneHref: string;
  email: string;
  city: string;
  state: string;
  serviceAreaLabel: string;
  services: Service[];
  offers: Offer[];
  serviceAreas: ServiceArea[];
  logoPath: string;
  usp: string;
};

export const facts: ClientFacts = {
  companyName: "Pure Home 365",
  tagline: "Clean Water, Customized for Your Home",
  phone: "828-532-2015",
  phoneHref: "tel:8285322015",
  email: "robs@purehome365.com",
  city: "Asheville",
  state: "NC",
  serviceAreaLabel: "Asheville, NC and surrounding communities within 80 miles",
  usp: "We customize our systems to meet your needs whether on a well or municipal water. We sell a variety of solutions to give you an option as to what fits your needs and budget. We are a local company invested in our community.",
  logoPath: "/images/logo.png",
  services: [
    {
      name: "Water Filtration",
      slug: "water-filtration",
      description: "Whole-home and point-of-use filtration systems that remove chlorine, sediment, heavy metals, and contaminants from your water supply.",
      blurb: "Remove chlorine, sediment, and contaminants from every tap in your home.",
    },
    {
      name: "Water Softeners",
      slug: "water-softeners",
      description: "High-efficiency water softeners that eliminate hard water minerals, protect your appliances, and leave your skin and hair feeling noticeably better.",
      blurb: "Eliminate scale buildup, protect appliances, and enjoy softer skin and hair.",
    },
    {
      name: "Water Filters",
      slug: "water-filters",
      description: "Under-sink and countertop filters that deliver great-tasting, pure drinking water right at your tap without the waste of bottled water.",
      blurb: "Crystal-clear drinking water at your tap. No bottles, no hassle.",
    },
    {
      name: "Well Water Treatment",
      slug: "well-water",
      description: "Specialized well water systems that address iron, bacteria, hardness, and other issues specific to private well sources in Western North Carolina.",
      blurb: "Iron, bacteria, hardness, and more. Engineered for Western NC wells.",
    },
  ],
  offers: [
    {
      headline: "Whole Home System — $0 Down",
      detail: "$96/month after credit approval. No upfront cost to protect your whole home.",
    },
    {
      headline: "$500 Off When You Pay by Card",
      detail: "Buy your whole-home system today and save $500 when paid by credit card.",
    },
    {
      headline: "$200 Off Point-of-Use Systems",
      detail: "Save $200 on any point-of-use filtration system for drinking water.",
    },
  ],
  serviceAreas: [
    { city: "Asheville", state: "NC" },
    { city: "Weaverville", state: "NC" },
    { city: "Arden", state: "NC" },
    { city: "Black Mountain", state: "NC" },
    { city: "Swannanoa", state: "NC" },
    { city: "Hendersonville", state: "NC" },
    { city: "Brevard", state: "NC" },
    { city: "Marion", state: "NC" },
    { city: "Morganton", state: "NC" },
    { city: "Waynesville", state: "NC" },
    { city: "Sylva", state: "NC" },
    { city: "Franklin", state: "NC" },
    { city: "Burnsville", state: "NC" },
    { city: "Spruce Pine", state: "NC" },
    { city: "Lenoir", state: "NC" },
  ],
};
